name: Javadoc

on:
  pull_request:

jobs:
  build:
    name: Test on JDK ${{ matrix.java_version }}/${{ matrix.linter }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        java_version: [8, 9, 11, 14, 15, 16-ea]
        linter: [ "", "-Xdoclint" ]

    steps:
    - name: Checkout for build
      uses: actions/checkout@v2.3.3
    - name: Set up JDK ${{ matrix.java_version }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java_version }}
    - name: Run javadoc
      run: ./jd.sh ${{ matrix.linter }}

